version: "3.8"
services:
  server1:
    image: server
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server1
    env_file: .env
    ports:
      - "8888:${SERVER_PORT}"

  server2:
    image: server
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server2
    env_file: .env
    ports:
      - "8889:${SERVER_PORT}"

  server3:
    image: server
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server3
    env_file: .env
    ports:
      - "8890:${SERVER_PORT}"

  nginx:
    image: nginx
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    depends_on:
      - server1
      - server2
      - server3
